Added data samples, refactored BS_helper
mathieugrasland/Brawlstar-Club-Dashboard pull request #3
Opened 2022-05-16 17:31 UTC by odysseu

Does not affect production branch

What was done in dev branch:

- Added short data_sample for player and club. This is open data anyway
- Refactored conditions and affectations in `for` loop in the `BS_helper` python `class`.

2022-05-16 19:25 UTC, mathieugrasland requested changes
Code refactorization isn't that great.

Delete package we need for secrets.

Data is good to add. (useless btw but ok)

2022-05-17 07:10 UTC, odysseu reviewed
Only approve what you're sure works.
Skip weird impletentation of code and erase of imports by Pycharm.

2022-05-17 07:10 UTC, odysseu commented on create_table/main.py
> -from google.cloud import secretmanager
Pycharm mistake. Since `secretmanager` was not used in this file, Pycharm erased the import.

2022-05-17 07:10 UTC, odysseu commented on extract_upload_logs/BS_helper.py
> -import pandas as pd
Pycharm mistake. Since `pandas` was not used, Pycharm erased the import.

2022-05-17 07:10 UTC, odysseu commented on extract_upload_logs/BS_helper.py
> +        dataframe = bqclient.query(query_string).result(
Weird Pycharm way to display code.

2022-05-17 09:56 UTC, closed without merging